# Generated by Django 3.2.8 on 2023-03-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PizzaModel',
        ),
        migrations.DeleteModel(
            name='ToppingsModel',
        ),
    ]
